name: InviteU
main: CKylin\InviteU\Main
version: 1.0.3
api: [1.0.0]
load: POSTWORLD
author: CKylinMC
commands:
 i:
  description: "邀请码"
  usage: "/i <invite code>"
  permission: i.cmd.i
 iu:
  description: "管理"
  usage: "/iu <options> <value>"
  permission: i.cmd.iu
permissions:
 i.cmd.i:
  description: "玩家兑换权限"
  default: true
 i.cmd.iu:
  description: "OP管理权限"
  default: OP
  